/**
 * Day briefings: NotebookLM audio overviews of each programme day, generated by the
 * site owner from the official agenda. Transcripts, chapters and the loudness envelope
 * come from scripts/podcasts/build.py (data/podcasts.generated.json).
 */
import generated from "@/data/podcasts.generated.json";
import { days, sessionById } from "./data";
import { podcastAudioSrc } from "@/lib/podcast-src";
import type { Session, Track } from "@/types";

export type Word = { text: string; start: number; end: number };
export type Chapter = { title: string; start: number; word: number; session: Session | null };
export type Envelope = { fps: number; frames: number; data: string };

export type Episode = {
  date: string;
  dayNumber: number;
  label: string;
  track: Track;
  available: boolean;
  audio: string;
  duration: number;
  words: Word[];
  sentences: [number, number][];
  chapters: Chapter[];
  envelope: Envelope | null;
};

type Gen = {
  episodes: {
    date: string;
    duration: number;
    words: [string, number, number][];
    sentences: [number, number][];
    chapters: { title: string; w: number; session: string | null }[];
    envelope: Envelope;
  }[];
};

const gen = generated as unknown as Gen;

export const episodes: Episode[] = days
  .filter((d) => d.track !== "opening")
  .map((d) => {
    const g = gen.episodes.find((e) => e.date === d.date);
    const words: Word[] = g ? g.words.map(([text, s, e]) => ({ text, start: s / 1000, end: e / 1000 })) : [];
    return {
      date: d.date,
      dayNumber: d.dayNumber,
      label: d.label,
      track: d.track,
      available: !!g,
      audio: g ? podcastAudioSrc(d.date) : "",
      duration: g?.duration ?? 0,
      words,
      sentences: g?.sentences ?? [],
      chapters: g
        ? g.chapters.map((c) => ({
            title: c.title,
            word: c.w,
            start: Math.max(0, (words[c.w]?.start ?? 0) - 0.15),
            session: c.session ? sessionById.get(c.session) ?? null : null,
          }))
        : [],
      envelope: g?.envelope ?? null,
    };
  });

export const episodeByDate = new Map(episodes.map((e) => [e.date, e]));
export const availableEpisodes = episodes.filter((e) => e.available);

/** Episode to suggest by default: the first available briefing for today or later, else the first. */
export const suggestedEpisode = (today: string) =>
  availableEpisodes.find((e) => e.date >= today) ?? availableEpisodes[0];

/** Index of the last word that has started at time t (-1 before the first word). */
export function wordAt(ep: Episode, t: number) {
  const w = ep.words;
  let lo = 0, hi = w.length - 1, ans = -1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (w[mid].start <= t) { ans = mid; lo = mid + 1; } else hi = mid - 1;
  }
  return ans;
}

export const sentenceOf = (ep: Episode, wi: number) => {
  if (wi < 0) return 0;
  const i = ep.sentences.findIndex(([a, b]) => wi >= a && wi <= b);
  return i < 0 ? ep.sentences.length - 1 : i;
};

export const chapterAt = (ep: Episode, t: number) => {
  let idx = 0;
  ep.chapters.forEach((c, i) => { if (c.start <= t) idx = i; });
  return idx;
};

const decoded = new Map<string, Uint8Array>();
function bytes(ep: Episode) {
  if (!ep.envelope) return null;
  let b = decoded.get(ep.date);
  if (!b) {
    const bin = atob(ep.envelope.data);
    b = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) b[i] = bin.charCodeAt(i);
    decoded.set(ep.date, b);
  }
  return b;
}

export const CHANNELS = 5; // rms, low, mid, high, pitch (each 0..1)

/** Envelope values at time t, linearly interpolated. Writes into `out` to avoid allocation. */
export function sampleEnvelope(ep: Episode, t: number, out: number[]) {
  const b = bytes(ep);
  if (!b || !ep.envelope) { out.fill(0); return out; }
  const f = Math.max(0, Math.min(ep.envelope.frames - 1.001, t * ep.envelope.fps));
  const i = Math.floor(f), k = f - i;
  for (let c = 0; c < CHANNELS; c++) out[c] = (b[i * CHANNELS + c] * (1 - k) + b[(i + 1) * CHANNELS + c] * k) / 255;
  return out;
}

/** Loudness peaks for a waveform of n bars (0..1). */
export function peaks(ep: Episode, n: number) {
  const b = bytes(ep);
  if (!b || !ep.envelope) return new Array(n).fill(0.1);
  const per = ep.envelope.frames / n;
  const out: number[] = [];
  for (let i = 0; i < n; i++) {
    let m = 0;
    for (let f = Math.floor(i * per); f < Math.floor((i + 1) * per); f++) m = Math.max(m, b[f * CHANNELS] / 255);
    out.push(Math.max(0.06, Math.pow(m, 1.4)));
  }
  return out;
}

export const fmtClock = (s: number) => {
  const t = Math.max(0, Math.floor(s));
  return `${Math.floor(t / 60)}:${String(t % 60).padStart(2, "0")}`;
};
